import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AppProviders } from './AppProviders';

import { dehydrate, HydrationBoundary } from '@tanstack/react-query';
import { getQueryClient } from '@/get-query-client';

import { getTodos } from '@/get-todos';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = getQueryClient();

  queryClient.prefetchQuery({
    queryKey: ['todos'],
    queryFn: getTodos,
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProviders>
          <HydrationBoundary state={dehydrate(queryClient)}>
            {children}
          </HydrationBoundary>
        </AppProviders>
      </body>
    </html>
  );
}
